# Generated by Django 5.1.2 on 2024-11-08 21:27

from django.db import migrations

def add_preset_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    preset_categories = [
        # Expense Categories
        {"name": "Rent", "type": "Expense"},
        {"name": "Mortgage", "type": "Expense"},
        {"name": "Utilities", "type": "Expense"},
        {"name": "Fuel", "type": "Expense"},
        {"name": "Public Transit", "type": "Expense"},
        {"name": "Groceries", "type": "Expense"},
        {"name": "Restaurants", "type": "Expense"},
        {"name": "Grooming", "type": "Expense"},
        {"name": "Skincare", "type": "Expense"},
        {"name": "Health Insurance", "type": "Expense"},
        {"name": "Prescriptions", "type": "Expense"},
        {"name": "Subscriptions", "type": "Expense"},
        {"name": "Movies", "type": "Expense"},
        {"name": "Credit Card", "type": "Expense"},
        {"name": "Loans", "type": "Expense"},
        {"name": "Retirement", "type": "Expense"},
        {"name": "Stocks", "type": "Expense"},
        {"name": "Miscellaneous", "type": "Expense"},
        {"name": "Other", "type": "Expense"},
        # Income Categories
        {"name": "Salary", "type": "Income"},
        {"name": "Savings", "type": "Income"},
        {"name": "Bonuses", "type": "Income"},
        {"name": "Side Gigs", "type": "Income"},
        {"name": "Contract Work", "type": "Income"},
        {"name": "Dividends", "type": "Income"},
        {"name": "Stock Sales", "type": "Income"},
        {"name": "Family Support", "type": "Income"},
        {"name": "Property Rental", "type": "Income"},
        {"name": "Refunds", "type": "Income"},
        {"name": "Prizes", "type": "Income"},
        {"name": "Other", "type": "Income"},
    ]

    for category in preset_categories:
        Category.objects.get_or_create(name=category["name"], type=category["type"], user=None)

class Migration(migrations.Migration):
    dependencies = [
        # Replace '0001_initial' with the name of your initial migration file if different
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_preset_categories),
    ]
