# Generated by Django 5.1.2 on 2024-11-05 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.category'),
        ),
    ]
